apiVersion: v1
kind: ConfigMap
metadata:
  name: data-config
  namespace: db
data:
  REDIS_PORT: "6379"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: data-secrets
  namespace: db
type: Opaque
data:
  # Values are base64 encoded (password123)
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  REDIS_PASSWORD: cGFzc3dvcmQxMjM=
